const blogPosts = [
    {
        title: "Think With Niche",
        date: "Published on October 14 , 2023",
        content: "Discover the latest news, trends, and insights from the global startup ecosystem. From innovation stories to entrepreneurial journeys, Think With Niche brings you in-depth analysis and thought leadership in the world of startups. Join us to stay ahead in this dynamic business landscape. ",
        image:"https://i1.feedspot.com/200/5680779.jpg?t=1695901994", 
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5680779&q=site:https%3A%2F%2Fwww.thinkwithniche.com%2Ffeed-rss.xml",
    },
    {
        title: "WISH-TV",
        date: "Published on October 15, 2023",
        content: "WISH-TV and the News 8 brand deliver the latest breaking news information and alert you and your family to issues impacting your life.",
        image:"https://i1.feedspot.com/200/5131479.jpg?t=1669277533",
        url:"https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5131479&q=site:https%3A%2F%2Fwww.wishtv.com%2Ffeed%2F",
    },
    {
        title: "Binary Tides",
        date: "Published on October 16, 2023",
        content: "Get Linux tutorials, free resources and news on Linux, Ubuntu, Fedora, Mint and more.",
        image:"https://i1.feedspot.com/200/209856.jpg?t=1615803067",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=209856&q=site:https%3A%2F%2Frss2.feedspot.com%2Fhttps%253A%252F%252Fwww.binarytides.com%252F",
    },
    {
        title: "Two Twenty One",
        date: "Published on October 16, 2023",
        content: "Two Twenty One is a DIY home and lifestyle blog, where Chelsea shares her home improvement projects, crafts, recipes, home & seasonal decor ideas, organization ideas, tips & tricks, and more. Chelsea, the author of Two Twenty One, is a millennial wife and mom living in Indianapolis, Indiana.",
        image:"https://i1.feedspot.com/200/4899316.jpg?t=1612772663",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=4899316&q=site:https%3A%2F%2Fwww.twotwentyone.net%2Ffeed%2F",
    },
    {
        title: "Namaste UI",
        date: "Published on October 16, 2023",
        content: "Namaste UI is a technology blog from India covering topics on blogging, business, digital marketing, SEO, and finance. Increase your reach by guest blogging. With the help of Namaste UI's guest post services, reach your brand presence to a broader range of audience.",
        image:"https://i1.feedspot.com/200/5366672.jpg?t=1688364597",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5366672&q=site:https%3A%2F%2Fwww.namasteui.com%2Ffeed%2F",
    },
    {
        title: "Echoes of Indiana Avenue",
        date: "Published on October 16, 2023",
        content: "Narrated by musician Herman 'Butch' Slaughter and produced by Cultural Manifesto host Kyle Long, Echoes of Indiana Avenue is a weekly audio documentary from WFYI. Each episode focuses on the cultural achievements of Black artists and musicians from central Indiana. Explore the cultural achievements of Black artists and musicians from central Indiana.",
        image:"https://i1.feedspot.com/200/5263496.jpg?t=1617255877",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5263496&q=site:https%3A%2F%2Fwww.wfyi.org%2Fprograms%2Fechoes-indiana-avenue%2Fradio%2Frss",
    },
    {
        title: "Indy's Child Parenting Magazine",
        date: "Published on October 16, 2023",
        content: "Indy's Child Parenting Magazine is a local and nationally award-winning parenting magazine. Discover the latest local to-dos or parenting support how-tos! Their mission is to educate, update and inform parents by providing them the tools, resources, events and contacts they need to make parenthood a little easier.",
        image:"https://i1.feedspot.com/200/4899556.jpg?t=1612772646",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=4899556&q=site:https%3A%2F%2Findyschild.com%2Ffeed%2F",
    },
    {
        title: "Gadget Gram",
        date: "Published on October 16, 2023",
        content: "Get the latest scoop on new gadgets and reviews from our experts only on Gadget Gram. See all the upcoming consumer electronics with full specs, features, and launch dates.",
        image:"https://i1.feedspot.com/200/5087008.jpg?t=1618549698",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5087008&q=site:https%3A%2F%2Fwww.gadgetgram.com%2Ffeed%2F",
    },
    {
        title: "Colts Blue Zone Podcast",
        date: "Published on October 16, 2023",
        content: "Join FOX59/CBS4's Mike Chappell and Dave Griffiths weekly as they discuss everything Colts from game recaps, to trade rumors.",
        image:"https://i1.feedspot.com/200/5194462.jpg?t=1631855152",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5194462&q=site:https%3A%2F%2Frss.art19.com%2Fcolts-blue-zone-podcast",
    },
    {
        title: "Invest Karo India",
        date: "Published on October 16, 2023",
        content: "In depth insights into capital markets and how to create wealth over time. Read Invest Karo India, by Tar, a Substack publication with tens of thousands of readers. Free in-depth research into various investing trends. I write cause it helps me think and understand these trends better in a disciplined manner.",
        image:"https://i1.feedspot.com/200/5293397.jpg?t=1656572992",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5293397&q=site:https%3A%2F%2Finvestkaroindia.substack.com%2Ffeed",
    },
    {
        title: "FLICKSIDE",
        date: "Published on October 16, 2023",
        content: "Find movie reviews, latest Indian movies, celebrity news and more at Flickside.",
        image:"https://i1.feedspot.com/200/4665944.jpg?t=1617782520",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=4665944&q=site:https%3A%2F%2Fflickside.com%2Ffeed%2F",
    },
    {
        title: "Oh My Dog",
        date: "Published on October 16, 2023",
        content: "Covers articles on health, training, animal welfare and products & reviews. Oh My Dog! is a blog for all things dog and a community for those of us who share our lives with these darling, four-legged fur-balls.",
        image:"https://i1.feedspot.com/200/1360947.jpg?t=1602676216",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=1360947&q=site:https%3A%2F%2Fohmydogblog.com%2Ffeed%2F",
    },
    {
        title: "Search Darjeeling",
        date: "Published on October 16, 2023",
        content: "Search Darjeeling is a local blog from Darjeeling, a tiny yet beautiful hill destination of India in the state of West Bengal. The objective of this blog is to share information that could bring at least a small difference to its visitors.",
        image:"https://i1.feedspot.com/200/5665601.jpg?t=1694065030",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5665601&q=site:https%3A%2F%2Fwww.searchdarjeeling.com%2Ffeeds%2Fposts%2Fdefault",
    },
    {
        title: "11Wickets",
        date: "Published on October 16, 2023",
        content: "Welcome to the world of fantasy sports. Stay up-to-date with daily fantasy cricket, IPL fantasy cricket league, and fantasy football league news, tricks and strategies to play accordingly.",
        image:"https://i1.feedspot.com/200/5091776.jpg?t=1621926420",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5091776&q=site:https%3A%2F%2Fblog.11wickets.com%2Ffeed%2F",
    },
    {
        title: "Indy Homes Blog",
        date: "Published on October 16, 2023",
        content: "Indy Homes Real Estate Blog covers home and real estate trends, info on the Indianapolis real estate market, buying and selling tips, Indianapolis fun and events, and more.The mission of the Indy Homes Team is to provide the utmost in service to our clients, and to have fun in the process. Team includes listing agents, buyer's agents, showings assistants, listing specialists and transaction coordinators.",
        image:"https://i1.feedspot.com/200/5306368.jpg?t=1627562464",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5306368&q=site:http%3A%2F%2Ffeeds.sierrainteractive.com%2Frss.ashx%2F12%2F685",
    },
    {
        title: "RG Infotech",
        date: "Published on October 16, 2023",
        content: "RG Infotech loves to share their thoughts on tech updates & news about web development, mobile application development & digital marketing. RG Infotech or Recursive Global Infotech Pvt. Ltd. was incorporated in 2007, with a mission of servicing IT services across the globe to grow online and spread beyond the geographical borders.",
        image:"https://i1.feedspot.com/200/5162576.jpg?t=1615883576",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5162576&q=site:https%3A%2F%2Fwww.rginfotech.com%2Ffeed",
    },
    {
        title: "Lucid Softech",
        date: "Published on October 16, 2023",
        content: "Get the latest news, tips & trends for Web Development & Internet Marketing.",
        image:"https://i1.feedspot.com/200/5053622.jpg?t=1605851760",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5053622&q=site:https%3A%2F%2Fwww.lucidsoftech.com%2Fblog%2Ffeed",
    },
    {
        title: "Tara Rochford Nutrition » Recipes",
        date: "Published on October 16, 2023",
        content: "Tara, a registered dietitian nutritionist, healthy lifestyle blogger, and certified personal & group fitness instructor shares healthy recipes for all seasons, nutrition tips, workouts, healthy living tips, and more.",
        image:"https://i1.feedspot.com/200/5314487.jpg?t=1629551795",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5314487&q=site:https%3A%2F%2Ftararochfordnutrition.com%2Fcategory%2Frecipes%2Ffeed%2F",
    },
    {
        title: "ReachIvy Blog",
        date: "Published on October 16, 2023",
        content: "Are you planning to study abroad? Read these blogs to use our tips & advice and get an admit in your dream school. ReachIvy is a premium education and careers advisory that helps aspiring students get accepted into Ivy League and other top schools globally.",
        image:"https://i1.feedspot.com/200/4590534.jpg?t=1615362060",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=4590534&q=site:https%3A%2F%2Fwww.reachivy.com%2Fcategory%2Fstudy-abroad%2Ffeed",
    },
    {
        title: "VarnaChitra",
        date: "Published on October 16, 2023",
        content: "This blog contains paintings depicting landscapes, nature, still life, figurative paintings and creative works in contemporary style. Most of the paintings are acrylic paintings done in realistic oil painting style, either on acid free paper or on canvas. There are also works in watercolor, graphite pencil, charcoal pencil, colored pencil, pastels and crayons.",
        image:"https://i1.feedspot.com/200/4977300.jpg?t=1622018561",
        url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=4977300&q=site:https%3A%2F%2Fwww.varnachitra.com%2Ffeeds%2Fposts%2Fdefault%3Falt%3Drss",
    },
  
  ];
  export default blogPosts;